### PR TITLE
Feature - remove intermediary log properties before forwarding to telemetry

### LINKED ISSUE #81: Remove unnecessary custom properties from the dependency tracking
**Is your feature request related to a problem? Please describe.**
Some custom properties are set to create a `DependencyTelemetry` instance in the `CustomDependencyTelemetryConverter`, but they remain there when they should actually be removed.

**Describe the solution you'd like**
These properties should be removed after the creation of the `DependencyTelemetry` instance:
- `DependencyDuration`
- `DependencyStartTime`

### PR DESCRIPTION
**Pull request by stijnmoreels**
Closes #81

### CODE REVIEW

**Comment by stijnmoreels** [comment]
Cleaner details now:
image

**Comment by stijnmoreels** [comment]
> LGTM, one question - What is `EventDescription`? I presume this is passed via context properties?

That's I think the telemetry context I think.

**Comment by tomkerkhove** [comment]
Nitpick - Can we rename it?

**Comment by stijnmoreels** [comment]
> Nitpick - Can we rename it?

Yes, we can, it will effect other telemetry too of course. `EventContext`?

**Comment by stijnmoreels** [comment]
We can remove it too, of course, since it's a duplication.

**Comment by tomkerkhove** [comment]
I thought it was passed here: https://github.com/arcus-azure/arcus.observability/blob/master/src/Arcus.Observability.Tests.Integration/Serilog/ApplicationInsightsSinkTests.cs#L162

But looks like it's coming from https://github.com/arcus-azure/arcus.observability/blob/e8872f93b4d0b30691e14e71a0732caed69d0675/src/Arcus.Observability.Telemetry.Core/ContextProperties.cs#L32

Moving this to https://github.com/arcus-azure/arcus.observability/issues/83 so this can be closed.

**Pull request merged**
